// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: nsfw.proto

package nsfw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nsfw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type ClassifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drawing float64 `protobuf:"fixed64,1,opt,name=drawing,proto3" json:"drawing,omitempty"`
	Hentai  float64 `protobuf:"fixed64,2,opt,name=hentai,proto3" json:"hentai,omitempty"`
	Neutral float64 `protobuf:"fixed64,3,opt,name=neutral,proto3" json:"neutral,omitempty"`
	Porn    float64 `protobuf:"fixed64,4,opt,name=porn,proto3" json:"porn,omitempty"`
	Sexy    float64 `protobuf:"fixed64,5,opt,name=sexy,proto3" json:"sexy,omitempty"`
}

func (x *ClassifyReply) Reset() {
	*x = ClassifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nsfw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyReply) ProtoMessage() {}

func (x *ClassifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_nsfw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyReply.ProtoReflect.Descriptor instead.
func (*ClassifyReply) Descriptor() ([]byte, []int) {
	return file_nsfw_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyReply) GetDrawing() float64 {
	if x != nil {
		return x.Drawing
	}
	return 0
}

func (x *ClassifyReply) GetHentai() float64 {
	if x != nil {
		return x.Hentai
	}
	return 0
}

func (x *ClassifyReply) GetNeutral() float64 {
	if x != nil {
		return x.Neutral
	}
	return 0
}

func (x *ClassifyReply) GetPorn() float64 {
	if x != nil {
		return x.Porn
	}
	return 0
}

func (x *ClassifyReply) GetSexy() float64 {
	if x != nil {
		return x.Sexy
	}
	return 0
}

var File_nsfw_proto protoreflect.FileDescriptor

var file_nsfw_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x73, 0x66, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x73,
	0x66, 0x77, 0x22, 0x27, 0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0d,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x64, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x6e, 0x74, 0x61,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x6e, 0x74, 0x61, 0x69, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x6e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x65, 0x78, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x65, 0x78,
	0x79, 0x32, 0x49, 0x0a, 0x08, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x12, 0x3d, 0x0a,
	0x0d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x15,
	0x2e, 0x6e, 0x73, 0x66, 0x77, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6e, 0x73, 0x66, 0x77, 0x2e, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x61, 0x7a, 0x77,
	0x7a, 0x2f, 0x67, 0x69, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e,
	0x73, 0x66, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nsfw_proto_rawDescOnce sync.Once
	file_nsfw_proto_rawDescData = file_nsfw_proto_rawDesc
)

func file_nsfw_proto_rawDescGZIP() []byte {
	file_nsfw_proto_rawDescOnce.Do(func() {
		file_nsfw_proto_rawDescData = protoimpl.X.CompressGZIP(file_nsfw_proto_rawDescData)
	})
	return file_nsfw_proto_rawDescData
}

var file_nsfw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nsfw_proto_goTypes = []interface{}{
	(*ClassifyRequest)(nil), // 0: nsfw.ClassifyRequest
	(*ClassifyReply)(nil),   // 1: nsfw.ClassifyReply
}
var file_nsfw_proto_depIdxs = []int32{
	0, // 0: nsfw.Classify.ClassifyImage:input_type -> nsfw.ClassifyRequest
	1, // 1: nsfw.Classify.ClassifyImage:output_type -> nsfw.ClassifyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nsfw_proto_init() }
func file_nsfw_proto_init() {
	if File_nsfw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nsfw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nsfw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nsfw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nsfw_proto_goTypes,
		DependencyIndexes: file_nsfw_proto_depIdxs,
		MessageInfos:      file_nsfw_proto_msgTypes,
	}.Build()
	File_nsfw_proto = out.File
	file_nsfw_proto_rawDesc = nil
	file_nsfw_proto_goTypes = nil
	file_nsfw_proto_depIdxs = nil
}
