### 登陆接口
POST {{host}}/user/login
Content-Type: application/json

{
  "username" : "akazwz",
  "password" : "123456"
}

### 注册接口
POST {{host}}/user/register
Content-Type: application/json

{
  "username" : "zwz",
  "password" : "123456"
}