### 登陆接口:成功
POST {{host}}/base/login
Content-Type: application/json

{
  "username" : "akazwz",
  "password" : "123456"
}

### 登陆接口:失败
POST {{host}}/user/login
Content-Type: application/json

{
  "username" : "aka",
  "password" : "123456"
}

### 注册接口:成功
POST {{host}}/user/register
Content-Type: application/json

{
  "username" : "someone",
  "password" : "123456"
}

### 注册接口:失败
POST {{host}}/user/register
Content-Type: application/json

{
  "username" : "akazwz",
  "password" : "123456"
}